/obj/item/stack/cable_coil/random/Initialize()
	if(persistent_id)
		CUSTOM_SV("tmp_color", src.color)
	. = ..()
	if(persistent_id)
		src.color = LOAD_CUSTOM_SV("tmp_color")
		CLEAR_SV("tmp_color")

/obj/item/stack/cable_coil/cut/Initialize()
	if(persistent_id)
		CUSTOM_SV("tmp_amount", src.amount)
	. = ..()
	if(persistent_id)
		src.amount = LOAD_CUSTOM_SV("tmp_amount")
		CLEAR_SV("tmp_amount")
